# Configuracion de conexion SQL Server
# Cada companero puede editar solo este archivo si su PC es distinta

servidor=127.0.0.1
puerto=1433
base_datos=db_glasscore_management
usuario=glasscore_user
contrasena=Glasscore123

# Si usan instancia SQLEXPRESS sin puerto fijo, cambien a:
# servidor=localhost\\SQLEXPRESS
# puerto=
