package com.mycompany.examenvidrieria;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmAsignacionHerramientas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAsignacionHerramientas.class.getName());

    /**
     * Creates new form FrmAsignacionHerramientas
     */
    public FrmAsignacionHerramientas() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Glasscore - Asignacion de Herramientas");
        cargarHerramientas();
        cargarEmpleados();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbHerramienta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbEmpleado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsignaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ASIGNACION DE HERRAMIENTAS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 400, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Empleado:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 130, 100, 20);

        cmbHerramienta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbHerramienta);
        cmbHerramienta.setBounds(20, 90, 290, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Herramientas:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 100, 20);

        cmbEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbEmpleado);
        cmbEmpleado.setBounds(20, 160, 290, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Observaciones:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 200, 100, 16);

        txtObservaciones.addActionListener(this::txtObservacionesActionPerformed);
        jPanel1.add(txtObservaciones);
        txtObservaciones.setBounds(20, 230, 480, 90);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);
        jPanel1.add(btnRegresar);
        btnRegresar.setBounds(375, 340, 90, 23);

        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(this::btnAsignarActionPerformed);
        jPanel1.add(btnAsignar);
        btnAsignar.setBounds(42, 340, 90, 23);

        btnDevolver.setText("Devolver");
        btnDevolver.addActionListener(this::btnDevolverActionPerformed);
        jPanel1.add(btnDevolver);
        btnDevolver.setBounds(155, 340, 90, 23);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);
        jPanel1.add(btnLimpiar);
        btnLimpiar.setBounds(265, 340, 90, 23);

        tblAsignaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_Asignacion", "Herramienta", "Empleado", "Fecha_Salida", "Fecha_Devolucion", "Observaciones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAsignaciones);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 390, 610, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtObservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionesActionPerformed
    }//GEN-LAST:event_txtObservacionesActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
    try{
        if (cmbHerramienta.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "No hay herramientas disponibles");
            return;
        }
        if (cmbEmpleado.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado");
            return;
        }

        String datoHerramienta =
                cmbHerramienta
                .getSelectedItem()
                .toString();

        int idHerramienta =
                Integer.parseInt(
                        datoHerramienta
                        .split("-")[0]
                        .trim());

        String datoEmpleado =
                cmbEmpleado
                .getSelectedItem()
                .toString();

        int idEmpleado =
                Integer.parseInt(
                        datoEmpleado
                        .split("-")[0]
                        .trim());

        Connection con =
                ConexionDB.getConexion();

        String sql =
                "INSERT INTO asignacion_herramientas "
                + "(id_herramienta,"
                + "id_empleado,"
                + "fecha_salida,"
                + "observaciones) "
                + "VALUES "
                + "(?,?,GETDATE(),?)";

        PreparedStatement ps =
                con.prepareStatement(sql);

        ps.setInt(1,idHerramienta);
        ps.setInt(2,idEmpleado);
        ps.setString(
                3,
                txtObservaciones.getText());

        ps.executeUpdate();

        String sql2 =
                "UPDATE herramientas "
                + "SET disponibilidad='Asignada' "
                + "WHERE id_herramienta=?";

        PreparedStatement ps2 =
                con.prepareStatement(sql2);

        ps2.setInt(1,idHerramienta);

        ps2.executeUpdate();

        JOptionPane.showMessageDialog(
                this,
                "Herramienta asignada");

        cargarTabla();
        cargarHerramientas();

    }
    catch(HeadlessException | NumberFormatException | SQLException e){

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());
    }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    txtObservaciones.setText("");

    if(cmbHerramienta.getItemCount() > 0){

        cmbHerramienta.setSelectedIndex(0);
    }

    if(cmbEmpleado.getItemCount() > 0){

        cmbEmpleado.setSelectedIndex(0);
    }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       FrmHerramientas frm =
            new FrmHerramientas();

    frm.setVisible(true);

    this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
     try{

        int fila =
                tblAsignaciones.getSelectedRow();

        if(fila == -1){

            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una asignacion");

            return;
        }

        Object fechaDevolucion = tblAsignaciones.getValueAt(fila, 4);
        if (fechaDevolucion != null && !fechaDevolucion.toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Esta asignacion ya fue devuelta");
            return;
        }

        int idAsignacion =
                Integer.parseInt(
                        tblAsignaciones
                        .getValueAt(fila,0)
                        .toString());

        Connection con =
                ConexionDB.getConexion();

        String sqlBuscar =
                "SELECT id_herramienta "
                + "FROM asignacion_herramientas "
                + "WHERE id_asignacion=?";

        PreparedStatement psBuscar =
                con.prepareStatement(sqlBuscar);

        psBuscar.setInt(1,idAsignacion);

        ResultSet rs =
                psBuscar.executeQuery();

        int idHerramienta = 0;

        if(rs.next()){

            idHerramienta =
                    rs.getInt("id_herramienta");
        }

        String sqlActualizar =
                "UPDATE asignacion_herramientas "
                + "SET fecha_devolucion_real=GETDATE() "
                + "WHERE id_asignacion=?";

        PreparedStatement psActualizar =
                con.prepareStatement(sqlActualizar);

        psActualizar.setInt(1,idAsignacion);

        psActualizar.executeUpdate();

        String sqlHerramienta =
                "UPDATE herramientas "
                + "SET disponibilidad='Disponible' "
                + "WHERE id_herramienta=?";

        PreparedStatement psHerramienta =
                con.prepareStatement(sqlHerramienta);

        psHerramienta.setInt(
                1,
                idHerramienta);

        psHerramienta.executeUpdate();

        JOptionPane.showMessageDialog(
                this,
                "Herramienta devuelta correctamente");

        cargarTabla();
        cargarHerramientas();

    }
    catch(Exception e){

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());
    }

    }//GEN-LAST:event_btnDevolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAsignacionHerramientas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbEmpleado;
    private javax.swing.JComboBox<String> cmbHerramienta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAsignaciones;
    private javax.swing.JTextField txtObservaciones;
    // End of variables declaration//GEN-END:variables

    private void cargarEmpleados() {
        try{

        cmbEmpleado.removeAllItems();

        Connection con =
                ConexionDB.getConexion();

        String sql =
                "SELECT id_empleado,"
                + "nombre,"
                + "apellido "
                + "FROM empleados "
                + "WHERE estado='Activo'";

        PreparedStatement ps =
                con.prepareStatement(sql);

        ResultSet rs =
                ps.executeQuery();

        while(rs.next()){

            cmbEmpleado.addItem(

                rs.getInt("id_empleado")
                + " - "
                + rs.getString("nombre")
                + " "
                + rs.getString("apellido")

            );
        }

    }
    catch(SQLException e){

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());
    }
}

    private void cargarTabla() {
        try{

        DefaultTableModel modelo =
                (DefaultTableModel)
                tblAsignaciones.getModel();

        modelo.setRowCount(0);

        Connection con =
                ConexionDB.getConexion();

        String sql =
                "SELECT a.id_asignacion,"
                + "h.nombre_herramienta,"
                + "e.nombre + ' ' + e.apellido AS empleado,"
                + "a.fecha_salida,"
                + "a.fecha_devolucion_real,"
                + "a.observaciones "
                + "FROM asignacion_herramientas a "
                + "INNER JOIN herramientas h "
                + "ON a.id_herramienta=h.id_herramienta "
                + "INNER JOIN empleados e "
                + "ON a.id_empleado=e.id_empleado";

        PreparedStatement ps =
                con.prepareStatement(sql);

        ResultSet rs =
                ps.executeQuery();

        while(rs.next()){

            modelo.addRow(new Object[]{

                rs.getInt("id_asignacion"),
                rs.getString("nombre_herramienta"),
                rs.getString("empleado"),
                rs.getString("fecha_salida"),
                rs.getString("fecha_devolucion_real"),
                rs.getString("observaciones")

            });

        }

    }
    catch(SQLException e){

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());
    }
}

    private void cargarHerramientas() {
         try{

        cmbHerramienta.removeAllItems();

        Connection con =
                ConexionDB.getConexion();

        String sql =
                "SELECT id_herramienta,"
                + "nombre_herramienta "
                + "FROM herramientas "
                + "WHERE disponibilidad='Disponible'";

        PreparedStatement ps =
                con.prepareStatement(sql);

        ResultSet rs =
                ps.executeQuery();

        while(rs.next()){

            cmbHerramienta.addItem(

                rs.getInt("id_herramienta")
                + " - "
                + rs.getString("nombre_herramienta")

            );
        }

    }
    catch(SQLException e){

        JOptionPane.showMessageDialog(
                this,
                e.getMessage());
    }
}
}