package com.mycompany.examenvidrieria;

import javax.swing.JOptionPane;

public class PanelPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PanelPrincipal.class.getName());

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        
        setTitle("Glasscore");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnEmpleados = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnHerramientas = new javax.swing.JButton();
        btnCotizaciones = new javax.swing.JButton();
        btnPlanillas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(89, 165, 241));
        jPanel3.setLayout(null);

        btnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEmpleados.setText("EMPLEADOS");
        btnEmpleados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEmpleados.addActionListener(this::btnEmpleadosActionPerformed);
        jPanel3.add(btnEmpleados);
        btnEmpleados.setBounds(50, 100, 120, 50);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("USUARIOS");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(this::btnUsuariosActionPerformed);
        jPanel3.add(jButton2);
        jButton2.setBounds(50, 40, 120, 50);

        btnHerramientas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHerramientas.setText("HERRAMIENTAS");
        btnHerramientas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHerramientas.addActionListener(this::btnHerramientasActionPerformed);
        jPanel3.add(btnHerramientas);
        btnHerramientas.setBounds(50, 160, 120, 52);

        btnCotizaciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCotizaciones.setText("COTIZACIONES");
        btnCotizaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCotizaciones.addActionListener(this::btnCotizacionesActionPerformed);
        jPanel3.add(btnCotizaciones);
        btnCotizaciones.setBounds(50, 220, 120, 50);

        btnPlanillas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPlanillas.setText("PLANILLAS");
        btnPlanillas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPlanillas.addActionListener(this::btnPlanillasActionPerformed);
        jPanel3.add(btnPlanillas);
        btnPlanillas.setBounds(50, 280, 120, 50);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSalir.addActionListener(this::btnSalirActionPerformed);
        jPanel3.add(btnSalir);
        btnSalir.setBounds(50, 340, 120, 50);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 220, 420);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("GLASSCORE");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(310, 140, 210, 90);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setText("Sistema de Vidrieria");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(340, 210, 140, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        FrmEmpleados frm = new FrmEmpleados();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {
        FrmUsuarios frm = new FrmUsuarios();
        frm.setVisible(true);
        this.dispose();
    }

    private void btnHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHerramientasActionPerformed
    FrmHerramientas frm =
            new FrmHerramientas();

    frm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnHerramientasActionPerformed

    private void btnCotizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCotizacionesActionPerformed
       FrmCotizaciones frm =
            new FrmCotizaciones();

    frm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnCotizacionesActionPerformed

    private void btnPlanillasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanillasActionPerformed
      FrmPlanillas frm =
            new FrmPlanillas();

    frm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnPlanillasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    int opcion =
    JOptionPane.showConfirmDialog(
    this,
    "Desea salir del sistema?",
    "Confirmacion",
    JOptionPane.YES_NO_OPTION);

    if(opcion == JOptionPane.YES_OPTION){

        System.exit(0);

    }
    
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PanelPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCotizaciones;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnHerramientas;
    private javax.swing.JButton btnPlanillas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
